---
- name: Copy patch file
  copy: src=elasticsearch_initd_patch
        dest=/tmp/elasticsearch_initd_patch

- name: Fix Elasticsearch PID dir
  patch: src=/tmp/elasticsearch_initd_patch
         dest=/etc/init.d/elasticsearch
         remote_src=true
  notify: restart elasticsearch

- name: Fix Graylog web defaults
  template: src=graylog.web.default.j2 dest=/etc/default/graylog-web owner=graylog group=graylog mode=0644
  notify: restart graylog-web