---

- name: Create RayCrafter master server
  hosts: masterservers
  sudo: yes
  sudo_user: root
  remote_user: vagrant
  vars_files:
    - env_vars/secret.yml
    - env_vars/base.yml
    - env_vars/masterserver.yml
  roles:
    - supervisor
    - jdauphant.ssl-certs
    - jdauphant.nginx
    - f500.elasticsearch
    - graylog2.graylog
    - db
    - rabbitmq
    - gunicorn
    - web
    - graylog
