---

- name: Deploy {{ application_name }}
  hosts: all
  sudo: yes
  sudo_user: root
  remote_user: david
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/dev.yml
    - env_vars/elasticsearch.yml
    - env_vars/nginx.yml

  roles:
    - base
    - jdauphant.ssl-certs
    - jdauphant.nginx
    - db
    - rabbitmq
    - web
    - celery
    - f500.elasticsearch
    - graylog2.graylog