---

- name: Deploy {{ application_name }}
  hosts: masterservers
  sudo: yes
  sudo_user: root
  vars_files:
    - env_vars/secret.yml
    - env_vars/production.yml

  roles:
    - base
    - supervisor
    - jdauphant.ssl-certs
    - jdauphant.nginx
    - f500.elasticsearch
    - graylog2.graylog
    - graylog
    - db
    - rabbitmq
    - web
    - celery
