---

- name: Common base role
  hosts: all
  sudo: yes
  sudo_user: root
  remote_user: vagrant
  vars_files:
    - env_vars/secret.yml
    - env_vars/base.yml
  roles:
    - base

- name: Create RayCrafter master server
  hosts: masterservers
  sudo: yes
  sudo_user: root
  remote_user: vagrant
  vars_files:
    - env_vars/secret.yml
    - env_vars/base.yml
    - env_vars/masterserver.yml
  roles:
    - supervisor
    - jdauphant.ssl-certs
    - jdauphant.nginx
    - f500.elasticsearch
    - graylog2.graylog
    - db
    - rabbitmq
    - web
    - celery
    - graylog
    - gridftp

- name: Create RayCrafter crafter node
  hosts: [crafternodes, masterservers]
  sudo: yes
  sudo_user: root
  remote_user: vagrant
  vars_files:
    - env_vars/secret.yml
    - env_vars/base.yml
    - env_vars/crafternode.yml
  roles:
    - {role: supervisor, when: "'crafternodes' in group_names"}
    - {role: web, when: "'crafternodes' in group_names"}
    - {role: celery, when: "'crafternodes' in group_names"}

- name: Setup raycrafter at the HLRS
  hosts: hlrs
  sudo: no
  vars_files:
    - env_vars/hlrs.yml
  roles:
    - hlrsvenv