---

- name: Create a {{ application_name }} virtual machine via vagrant
  hosts: all
  sudo: yes
  sudo_user: root
  remote_user: vagrant
  vars_files:
    - env_vars/secret.yml
    - env_vars/vagrant.yml

  roles:
    - base
    - supervisor
    - jdauphant.ssl-certs
    - jdauphant.nginx
    - f500.elasticsearch
    - graylog2.graylog
    - graylogfix
    - db
    - rabbitmq
    - web
    - celery
    - graylog
