---

- name: Common base role
  hosts: all
  sudo: yes
  sudo_user: root
  remote_user: vagrant
  vars_files:
    - env_vars/secret.yml
    - env_vars/vagrant.yml

  roles:
    - base

#- name: Create a RayCrafter crafter node
#  hosts: crafternodes
#  sudo: yes
#  sudo_user: root
#  remote_user: vagrant
#  vars_files:
#    - env_vars/secret.yml
#    - env_vars/vagrant.yml
#
#  roles:
#    - base
#

- name: Create a RayCrafter master server
  hosts: masterservers
  sudo: yes
  sudo_user: root
  remote_user: vagrant
  vars_files:
    - env_vars/secret.yml
    - env_vars/vagrant.yml

  roles:
    - supervisor
    - jdauphant.ssl-certs
    - jdauphant.nginx
    - f500.elasticsearch
    - graylog2.graylog
    - db
    - rabbitmq
    - web
    - celery
    - graylog
    - gridftp

