---

celery_user: "{{ web_user }}"
celery_group: "{{ web_group }}"

celery_application_name: celery
celery_scripts_dir: "{{ virtualenv_path }}/scripts/celery"
celery_template_file: "{{ celery_application_name }}_start.j2"
celerycam_template_file: "celerycam_start.j2"
celery_worker_app: "{{ application_name }}"

celery_log_dir: "{{ virtualenv_path }}/logs"
celery_log_file: "{{ celery_log_dir }}/{{ celery_application_name }}.log"
celerycam_log_file: "{{ celery_log_dir }}/celerycam.log"

celery_num_workers: 2