---

- include: copy_scripts.yml

- include: setup_supervisor.yml

- name: Check running applications managed by supervisor
  shell: supervisorctl status
  register: supervisor_applications
  tags:
    - celery
    - supervisor

- name: Restart the {{ celery_application_name }} app
  set_fact: "{{ supervisor_restart_programms}} + [{{ celery_application_name }}]"
  when: supervisor_applications.stdout.find('{{ celery_application_name }}') != -1
  tags:
    - celery
    - supervisor

- name: Restart the celerycam app
  set_fact: "{{ supervisor_restart_programms}} + [celerycam]"
  when: supervisor_applications.stdout.find('celerycam') != -1
  tags:
    - celery
    - supervisor
