---

- name: Create the Supervisor config file for {{ celery_application_name }}
  template: src=supervisor_{{ celery_application_name }}.conf.j2
            dest=/etc/supervisor/conf.d/{{ celery_application_name }}.conf
  notify: Supervisor reread
  notify: Supervisor update
  tags:
    - celery

- name: Create the {{ celery_application_name }} log directory
  file: path={{ celery_log_dir }}
        owner={{ celery_user }}
        group={{ celery_group }}
        state=directory
  tags:
    - celery

- name: Create the {{ celery_application_name }} log file
  file: path={{ celery_log_file }}
        owner={{ celery_user }}
        group={{ celery_group }}
        state=touch
  tags:
    - celery