---
- name: Wait for Rest
  wait_for: host="127.0.0.1" port={{graylog_rest_port}}

- name: Add graylog inputs
  shell: "curl -s -X GET -H\"Content-Type: application/json\" http://{{ graylog_root_username }}:{{ graylog_root_password_unencrypted }}@{{ graylog_rest_adress }}/system/inputs | jq \".inputs| .[] | .message_input | .title\" | grep '\"{{item}}\"' && curl -X POST -H \"Content-Type: application/json\" -d \"`cat /tmp/{{item}}.json`\" http://{{ graylog_root_username }}:{{ graylog_root_password_unencrypted }}@{{ graylog_rest_adress }}/system/inputs"
  with_items: graylog_inputs.keys()
