---

- include: create_users_and_groups.yml

- include: setup_virtualenv.yml
  tags: virtualenv

- include: setup_git_repo.yml

- include: install_additional_packages.yml
  tags: packages

- include: setup_django_app.yml

- include: set_file_permissions.yml
