---

- name: Add java repository
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: Install java 8
  apt: name=oracle-java8-installer

- name: Add elasticsearch key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch id=D88E42B4

- name: Add elasticsearch repository
  apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/1.6/debian stable main'

- name: Install Elasticsearch
  apt: name=elasticsearch state=present

- name: Configuring Elasticsearch
  template: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml

- name: Install Supervisor
  apt: name=supervisor update_cache={{ update_apt_cache }} state=installed

- name: Ensure supervisor service is started
  service: name=supervisor state=started enabled=yes

- name: Create the Supervisor config file for elasticsearch
  template: src=supervisor_elasticsearch.conf.j2
            dest=/etc/supervisor/conf.d/elasticsearch.conf

- name: Re-read the Supervisor config files
  command: supervisorctl reread

- name: Update Supervisor to add the app in the process group
  command: supervisorctl update
