---

- name: Create inputs
  grayloginputs:
    title: "{{item}}"
    host: "192.168.33.15"
    configuration: "{{graylog_inputs[item]['configuration']}}"
    user: 'admin'
    password: 'admin'
    type: "{{graylog_inputs[item]['type']}}"
    node: "{{graylog_inputs[item]['node']}}"
  with_items: graylog_inputs.keys()
