---
- name: Wait for Rest
  wait_for: host="127.0.0.1" port={{graylog_rest_port}}

- name: Create inputs
  grayloginputs:
    title: "{{item}}"
    configuration: "{{graylog_inputs[item]['configuration']}}"
    host: "{{graylog_rest_ip}}"
    user: "{{graylog_root_username}}"
    password: "{{graylog_root_password_unencrypted}}"
    type: "{{graylog_inputs[item]['type']}}"
    node: "{{graylog_inputs[item]['node']}}"
  with_items: graylog_inputs.keys()

- name: Create content packs
  graylogcontentpack:
    srcjson: "{{item}}"
    host: "{{graylog_rest_ip}}"
    user: "{{graylog_root_username}}"
    password: "{{graylog_root_password_unencrypted}}"
  with_items: "{{graylog_contentpacks}}"
