---
- name: Wait for Rest
  wait_for: host={{graylog_rest_host}} port={{graylog_rest_port}}
  tags: graylog

- name: Create inputs
  grayloginputs:
    title: "{{item}}"
    configuration: "{{graylog_inputs[item]['configuration']}}"
    host: "{{graylog_rest_host}}"
    port: "{{graylog_rest_port}}"
    user: "{{graylog_root_username}}"
    password: "{{graylog_root_password_unencrypted}}"
    type: "{{graylog_inputs[item]['type']}}"
    node: "{{graylog_inputs[item]['node']}}"
  with_items: graylog_inputs.keys()
  tags: graylog

- name: Create content packs
  graylogcontentpack:
    srcjson: "{{item}}"
    host: "{{graylog_rest_host}}"
    port: "{{graylog_rest_port}}"
    user: "{{graylog_root_username}}"
    password: "{{graylog_root_password_unencrypted}}"
  with_items: "{{graylog_contentpacks}}"
  tags: graylog
