---

- name: Copy private ssh key of masterserver
  copy: src="{{playbook_dir}}/files/ssh/id_rsa" dest="{{ lookup('env','HOME') }}/.ssh/id_rsa_encrypted"
        owner={{ ansible_ssh_user }} mode=0700

- name: Decrypt private ssh key of masterserver
  command: openssl aes-256-cbc -salt -a -d -in {{ lookup('env','HOME') }}/.ssh/id_rsa_encrypted
           -out {{ lookup('env','HOME') }}/.ssh/id_rsa -k {{ ssh_key_password }}
           creates={{ lookup('env','HOME') }}/.ssh/id_rsa

- include: create_swap_file.yml
  when: create_swap_file
  tags: swap

- name: Update apt
  apt: update_cache={{ update_apt_cache }}
  tags: packages

- name: Ensure bash, OpenSSl, and libssl are the latest versions
  apt: name={{ item }} state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Install base packages
  apt: name={{ item }} force=yes state=installed
  with_items:
    - build-essential
    - ntp
    - htop
    - git
    - libpq-dev
    - python-dev
    - python-pip
    - python-pycurl
    - '{{ language_pack}}'
  tags: packages

- name: Install virtualenv
  pip: name=virtualenv
  tags: packages

- name: Make sure ntp is running
  service: name=ntp state=started enabled=yes
  tags: service

