---

- name: Install Memcached
  apt: name=memcached update_cache={{ update_apt_cache }} state=installed
  tags: [packages,memcached]

- name: Create the Memcached configuration file
  template: src=memcached.conf.j2
            dest=/etc/memcached.conf
            mode=0644
            backup=yes
  notify:
    - restart memcached
  tags: memcached

- name: Ensure the Memcached service is running
  service: name=memcached state=started enabled=yes
  tags: memcached